---
- hosts: ans
  become_user: root
  become: true
  tasks:
    - name: check the package installation
      command: php -v
      register: php_logs
      ignore_errors: true
    - name: display the logs
      debug: var=php_logs
    - name: php is not installed
      debug: msg='php is not installed'
      when: php_logs.changed == false
    - name: php is installed
      debug: msg='php is installed'
      when: php_logs.changed == true
